name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: "factureaza sandbox"
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3']
        enum: ['3', '4']
        laravel: ['8', '9', '10', '11']
        exclude:
          - php: '8.1'
            laravel: '10'
          - php: '8.1'
            laravel: '11'
    name: PHP ${{ matrix.php }} Laravel ${{ matrix.laravel }} Enum ${{ matrix.enum }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, json, sqlite3
          tools: composer:v2
      - name: Lock Package Versions
        run: |
          composer require "konekt/enum:${{ matrix.enum }}.*" --no-update -v
          composer require "illuminate/http:${{ matrix.laravel }}.*" --no-update -v
      - name: Composer Install
        run: composer install --prefer-dist --no-progress --no-interaction
      - name: Run Tests
        run: php vendor/bin/phpunit --testdox
